"""
empty message

Revision ID: 1f4631da751b
Revises: 946bada3d9d5
Create Date: 2017-05-24 20:19:54.896355
"""
from __future__ import absolute_import

# revision identifiers, used by Alembic.
revision = '1f4631da751b'
down_revision = '946bada3d9d5'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(u'fk_inherited_entity_id', 'sbe_event', 'entity', [u'id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'fk_inherited_entity_id', 'sbe_event', type_='foreignkey')
    # ### end Alembic commands ###
